backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'event'
    label: 'Event'
    folder: 'content/event'
    create: true
    slug: 'title'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    extension: 'json'
    format: 'json'
    editor:
      preview: false
    fields:
      - {
          label: 'Collection Type',
          name: 'type',
          widget: 'hidden',
          default: 'event',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Year',
          name: 'year',
          widget: 'datetime',
          date_format: 'YYYY',
          time_format: '',
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Images',
          name: 'images',
          widget: 'list',
          fields:
            [
              { label: 'Image', name: 'image', widget: 'image' },
              { label: 'Image Alt', name: 'imageAlt', widget: 'string' },
            ],
        }

  - name: 'executive'
    label: 'Executive Committee'
    folder: 'content/executive'
    create: true
    slug: 'members'
    media_folder: ''
    public_folder: ''
    path: 'members/index'
    extension: 'json'
    format: 'json'
    editor:
      preview: false
    fields:
      - {
          label: 'Collection Type',
          name: 'type',
          widget: 'hidden',
          default: 'executive',
        }
      - {
          label: 'Member',
          name: 'member',
          widget: 'list',
          fields:
            [
              { label: 'Name', name: 'name', widget: 'string' },
              { label: 'Position', name: 'position', widget: 'string' },
              { label: 'Photo', name: 'photo', widget: 'image' },
            ],
        }

  - name: 'committee'
    label: 'Committee'
    folder: 'content/committee'
    create: true
    slug: 'name'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    extension: 'json'
    format: 'json'
    editor:
      preview: false
    fields:
      - {
          label: 'Collection Type',
          name: 'type',
          widget: 'hidden',
          default: 'committee',
        }
      - { label: 'Committee Name', name: 'name', widget: 'string' }
      - {
          label: 'Chair',
          name: 'chair',
          widget: 'object',
          fields:
            [
              { label: 'Name', name: 'name', widget: 'string' },
              { label: 'Position', name: 'position', widget: 'string' },
              { label: 'Photo', name: 'photo', widget: 'image' },
            ],
        }
      - {
          label: 'Members',
          name: 'members',
          widget: 'list',
          field: { label: 'Member name', name: 'memberName', widget: 'string' },
        }

  - name: 'former'
    label: 'Former Officers'
    folder: 'content/former'
    create: true
    slug: 'name'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    extension: 'json'
    format: 'json'
    editor:
      preview: false
    fields:
      - {
          label: 'Collection Type',
          name: 'type',
          widget: 'hidden',
          default: 'former',
        }
      - { label: 'Academic Year', name: 'name', widget: 'string' }
      - {
          label: 'Officers',
          name: 'officers',
          widget: 'list',
          fields:
            [
              { label: 'Name', name: 'name', widget: 'string' },
              { label: 'Position', name: 'position', widget: 'string' },
            ],
        }
