const TextContentType = 'TEXT';
const ImageContentType = 'IMAGE';

const contentTypes = {
  TextContentType,
  ImageContentType,
};

const mostMemorableMomentContent = [
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Amatic SC',
    fontSize: 10,
    x: 14,
    y: 10,
    width: 100,
    height: 39,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Shadows Into Light',
    fontSize: 6,
    x: 137,
    y: 19,
    width: 48,
    height: 40,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Kalam',
    fontSize: 6,
    x: 250,
    y: 11,
    width: 100,
    height: 40,
    lineHeight: 1.6,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Architects Daughter',
    fontSize: 7,
    x: 22,
    y: 73,
    width: 157,
    height: 30,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Amita',
    fontSize: 6,
    x: 194,
    y: 59,
    width: 61,
    height: 61,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Nothing You Could Do',
    fontSize: 7,
    x: 27,
    y: 127,
    width: 40,
    height: 63,
    lineHeight: 1.3,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Merienda',
    fontSize: 4,
    x: 177,
    y: 150,
    width: 52,
    height: 24,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Sriracha',
    fontSize: 5,
    x: 240,
    y: 136,
    width: 105,
    height: 27,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Itim',
    fontSize: 6,
    x: 25,
    y: 200,
    width: 100,
    height: 28,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Nanum Pen',
    fontSize: 9,
    x: 25,
    y: 235,
    width: 110,
    height: 44,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Handlee',
    fontSize: 6,
    x: 144,
    y: 233,
    width: 88,
    height: 24,
    lineHeight: 1.5,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Patrick Hand',
    fontSize: 9,
    x: 252,
    y: 231,
    width: 100,
    height: 36,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Permanent Marker',
    fontSize: 7,
    x: 28,
    y: 362,
    width: 100,
    height: 30,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Covered By Your Grace',
    fontSize: 8,
    x: 139,
    y: 371,
    width: 48,
    height: 77,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Berkshire Swash',
    fontSize: 6,
    x: 239,
    y: 367,
    width: 100,
    height: 21,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Caveat',
    fontSize: 8,
    x: 202,
    y: 401,
    width: 100,
    height: 40,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Gochi Hand',
    fontSize: 4,
    x: 308,
    y: 429,
    width: 40,
    height: 35,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Pangolin',
    fontSize: 6,
    x: 38,
    y: 460,
    width: 96,
    height: 28,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Neucha',
    fontSize: 8,
    x: 155,
    y: 464,
    width: 64,
    height: 36,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Mali',
    fontSize: 5,
    x: 13,
    y: 507,
    width: 93,
    height: 28,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Indie Flower',
    fontSize: 8,
    x: 214,
    y: 521,
    width: 128,
    height: 36,
    lineHeight: 1,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Gloria Hallelujah',
    fontSize: 6,
    x: 111,
    y: 591,
    width: 137,
    height: 36,
    lineHeight: 1,
  },

  // Decorations
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsDecoration1.svg',
    rotation: 0,
    x: 286,
    y: 50,
    width: 29,
    height: 16,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsDecoration2.svg',
    rotation: 0,
    x: 17,
    y: 115,
    width: 54.55,
    height: 82.67,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsDecoration3.svg',
    rotation: 0,
    x: 153.19,
    y: 131.81,
    width: 26,
    height: 17,
  },

  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsDecoration4.svg',
    rotation: 0,
    x: 294.53,
    y: 210.26,
    width: 24,
    height: 13,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsDecoration5.svg',
    rotation: 0,
    x: 151,
    y: 264,
    width: 74,
    height: 11,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsDecoration6.svg',
    rotation: 0,
    x: 10,
    y: 372.76,
    width: 25,
    height: 24,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsDecoration7.svg',
    rotation: 0,
    x: 286.95,
    y: 453.47,
    width: 15.6,
    height: 13.57,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsDecoration8.svg',
    rotation: 0,
    x: 108.32,
    y: 485,
    width: 21.08,
    height: 19.69,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsDecoration9.svg',
    rotation: 0,
    x: 158,
    y: 576,
    width: 42,
    height: 9,
  },

  // Images
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsImage1.png',
    rotation: 0,
    x: 256,
    y: 74,
    width: 99.77,
    height: 54.84,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsImage2.png',
    rotation: 0,
    x: 87,
    y: 114,
    width: 67.7,
    height: 41.21,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsImage3.png',
    rotation: 0,
    x: 227,
    y: 176,
    width: 67.7,
    height: 47,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsImage4.png',
    rotation: 0,
    x: 16,
    y: 406,
    width: 78,
    height: 35.21,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsImage5.png',
    rotation: 0,
    x: 226,
    y: 464,
    width: 81.61,
    height: 51.87,
  },
  {
    contentType: ImageContentType,
    image: '/anniversary/2022/moments/momentsImage6.png',
    rotation: 0,
    x: 121,
    y: 506,
    width: 67.7,
    height: 39.21,
  },
];

export { mostMemorableMomentContent, contentTypes };
