const TextContentType = 'TEXT';

const mostMemorableMomentContent = [
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Amatic SC',
    fontSize: 10,
    x: 14,
    y: 10,
    width: 100,
    height: 39,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Shadows Into Light',
    fontSize: 6,
    x: 137,
    y: 19,
    width: 48,
    height: 40,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Kalam',
    fontSize: 6,
    x: 250,
    y: 11,
    width: 100,
    height: 40,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Architects Daughter',
    fontSize: 7,
    x: 22,
    y: 73,
    width: 157,
    height: 30,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Amita',
    fontSize: 6,
    x: 194,
    y: 59,
    width: 61,
    height: 61,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Nothing You Could Do',
    fontSize: 7,
    x: 27,
    y: 127,
    width: 40,
    height: 63,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Merienda',
    fontSize: 4,
    x: 177,
    y: 150,
    width: 52,
    height: 24,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Sriracha',
    fontSize: 5,
    x: 240,
    y: 136,
    width: 105,
    height: 27,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Itim',
    fontSize: 6,
    x: 25,
    y: 200,
    width: 100,
    height: 28,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Nanum Pen',
    fontSize: 9,
    x: 25,
    y: 235,
    width: 110,
    height: 44,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Handlee',
    fontSize: 6,
    x: 144,
    y: 233,
    width: 88,
    height: 24,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Patrick Hand',
    fontSize: 9,
    x: 252,
    y: 231,
    width: 100,
    height: 36,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Permanent Marker',
    fontSize: 7,
    x: 28,
    y: 362,
    width: 100,
    height: 30,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Covered By Your Grace',
    fontSize: 8,
    x: 139,
    y: 371,
    width: 48,
    height: 77,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Berkshire Swash',
    fontSize: 6,
    x: 239,
    y: 367,
    width: 100,
    height: 21,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Caveat',
    fontSize: 8,
    x: 202,
    y: 401,
    width: 100,
    height: 40,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Gochi Hand',
    fontSize: 4,
    x: 308,
    y: 429,
    width: 40,
    height: 35,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Pangolin',
    fontSize: 6,
    x: 38,
    y: 460,
    width: 96,
    height: 28,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment is when we get together and enjoy activities.',
    fontFamily: 'Neucha',
    fontSize: 8,
    x: 155,
    y: 464,
    width: 64,
    height: 36,
  },
  {
    contentType: TextContentType,
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    fontFamily: 'Mali',
    fontSize: 5,
    x: 13,
    y: 507,
    width: 93,
    height: 28,
  },
  {
    contentType: TextContentType,
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    fontFamily: 'Indie Flower',
    fontSize: 8,
    x: 214,
    y: 521,
    width: 128,
    height: 36,
  },
  {
    contentType: TextContentType,
    text: '',
    fontFamily: '',
    fontSize: 0,
    x: 0,
    y: 0,
    width: 0,
    height: 0,
  },
];

export { mostMemorableMomentContent };
