export default [
  {
    contentType: 'TEXT',
    text: 'By joining MCL-ACM I got a chance to make new friends as well as develop my social and programming skills.',
    x: 521,
    y: 83,
    width: 100,
    height: 21,
    fontFamily: 'Itim',
    fontSize: 6,
    lineHeight: 1,
    id: 1,
  },
  {
    contentType: 'TEXT',
    text: 'It helped me with my academics, as well as developing my programming skills',
    x: 368,
    y: 280,
    width: 85,
    height: 30,
    fontFamily: 'Caveat',
    fontSize: 8,
    lineHeight: 1.6,
    id: 2,
  },
  {
    contentType: 'TEXT',
    text: 'It let me explore various paths to improve upon myself',
    x: 570,
    y: 316,
    width: 45,
    height: 24,
    fontFamily: 'Covered By Your Grace',
    fontSize: 6,
    lineHeight: 1.6,
    id: 3,
  },
  {
    contentType: 'TEXT',
    text: 'I am more confident in leading, socializing, and communicating with seniors when I need help with my tasks.',
    x: 105,
    y: 69,
    width: 100,
    height: 40,
    fontFamily: 'Kalam',
    fontSize: 6,
    lineHeight: 1.6,
    id: 4,
  },
  {
    contentType: 'TEXT',
    text: 'It helps me benefit my studies and make social to my org mates',
    x: 86,
    y: 14,
    width: 46,
    height: 40,
    fontFamily: 'Mali',
    fontSize: 6,
    lineHeight: 1.4,
    id: 5,
  },
  {
    contentType: 'TEXT',
    text: 'It helped me with my studies',
    x: 262,
    y: 324,
    width: 46,
    height: 18,
    fontFamily: 'Permanent Marker',
    fontSize: 6,
    lineHeight: 1.8,
    id: 6,
  },
  {
    contentType: 'TEXT',
    text: 'MCL-ACM helped improve my ability to communicate with other people and learning technical topics about programming by being helped by my fellow members',
    x: 366,
    y: 81,
    width: 89,
    height: 48,
    fontFamily: 'Architects Daughter',
    fontSize: 8,
    lineHeight: 1.4,
    id: 7,
  },
  {
    contentType: 'TEXT',
    text: 'I learned to collaborate with different people and whenever you have problem on your acads-fellow acm members will try to help you.',
    x: 233,
    y: 281,
    width: 110,
    height: 28,
    fontFamily: 'Pangolin',
    fontSize: 7,
    lineHeight: 1.2,
    id: 8,
  },
  {
    contentType: 'TEXT',
    text: "They're a big help esp. sa exam, may review sessions na ginagawa and matututo ka kahit naglu-lurk lang 😅😂",
    x: 320,
    y: 19,
    width: 85,
    height: 44,
    fontFamily: 'Sriracha',
    fontSize: 6,
    lineHeight: 1.6,
    id: 9,
  },
  {
    contentType: 'TEXT',
    text: 'Joining MCL-ACM helped me connect with people more than what i currently have in my social bubble especially since we have our common interests.',
    x: 515,
    y: 233,
    width: 55,
    height: 56,
    fontFamily: 'Gochi Hand',
    fontSize: 6,
    lineHeight: 1,
    id: 10,
  },
  {
    contentType: 'TEXT',
    text: 'I was able to interact with people that have the same interest as me in terms of computing and tech.',
    x: 423,
    y: 36,
    width: 107,
    height: 39,
    fontFamily: 'Shadows Into Light',
    fontSize: 8,
    lineHeight: 1.5,
    id: 11,
  },
  {
    contentType: 'TEXT',
    text: 'It helped me become a better programmer. Being surrounded with amazing programmers, I got more motivated to be better',
    x: 214,
    y: 85,
    width: 89,
    height: 36,
    fontFamily: 'Patrick Hand',
    fontSize: 7,
    lineHeight: 1.5,
    id: 12,
  },
  {
    contentType: 'TEXT',
    text: 'It helped me think on how to answer programming challenges more efficiently and discover more frameworks and algorithms that are used in some situations.',
    x: 17,
    y: 84,
    width: 75,
    height: 65,
    fontFamily: 'Neucha',
    fontSize: 8,
    lineHeight: 1.2,
    id: 13,
  },
  {
    contentType: 'TEXT',
    text: 'It helps me to communicate better with others and learn new things from them',
    x: 209,
    y: 20,
    width: 100,
    height: 48,
    fontFamily: 'Merienda',
    fontSize: 8,
    lineHeight: 1.4,
    id: 14,
  },
  {
    contentType: 'TEXT',
    text: 'It helped me connect to great people that have the same interest as me.',
    x: 440,
    y: 321,
    width: 120,
    height: 24,
    fontFamily: 'Rock Salt',
    fontSize: 5,
    lineHeight: 2.5,
    id: 15,
  },
  {
    contentType: 'TEXT',
    text: 'It helps me improve my socializing skills and learn some programming lessons',
    x: 563,
    y: 14,
    width: 68,
    height: 36,
    fontFamily: 'Nothing You Could Do',
    fontSize: 7,
    lineHeight: 1,
    id: 16,
  },
  {
    contentType: 'TEXT',
    text: 'I think that it made me aware of what my skill and abilities are capable of.',
    x: 588,
    y: 170,
    width: 36,
    height: 56,
    fontFamily: 'Comic Neue',
    fontSize: 7,
    lineHeight: 1.3,
    id: 17,
  },
  {
    contentType: 'TEXT',
    text: 'MCL-ACM has helped me by getting to interact with like minded people that have an interest in the field of computing. Not only that, but MCL-ACM has events that piqued my interest.',
    x: 292,
    y: 233,
    width: 135,
    height: 44,
    fontFamily: 'Amatic SC',
    fontSize: 9,
    lineHeight: 1,
    id: 18,
  },
  {
    contentType: 'TEXT',
    text: 'As an MITL student, joining ACM helped me connect with CCIS students that has advance knowledge in the field of computing. Collaborating and having friendships along the way heheh',
    x: 11,
    y: 198,
    width: 116,
    height: 60,
    fontFamily: 'Gloria Hallelujah',
    fontSize: 6,
    lineHeight: 2,
    id: 19,
  },
  {
    contentType: 'TEXT',
    text: 'I made a lot of great friends and it made me confident socializing with others.',
    x: 133,
    y: 322,
    width: 88,
    height: 33,
    fontFamily: 'Handlee',
    fontSize: 8,
    lineHeight: 1,
    id: 20,
  },
  {
    contentType: 'TEXT',
    text: 'It help me to grow as a person especially when I became the president.',
    x: 148,
    y: 224,
    width: 124,
    height: 18,
    fontFamily: 'Berkshire Swash',
    fontSize: 7,
    lineHeight: 1.4,
    id: 21,
  },
  {
    contentType: 'TEXT',
    text: 'with all the seminars, peer mentoring, and my seniors willing to answer all of my questions related to coding, my coding journey was a breeze.',
    x: 516,
    y: 123,
    width: 73,
    height: 54,
    fontFamily: 'Nanum Pen Script',
    fontSize: 7,
    lineHeight: 1.4,
    id: 22,
  },
  {
    contentType: 'TEXT',
    text: 'Joining MCL-ACM helped me meet new people, improve my skills (programming, leadership, etc.), and go out of my comfort zone',
    x: 41,
    y: 287,
    width: 69,
    height: 50,
    fontFamily: 'Amita',
    fontSize: 5,
    lineHeight: 1.8,
    id: 23,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration1.svg',
    x: 467,
    y: 97,
    width: 33,
    height: 35,
    rotation: 0,
    id: 24,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration4.svg',
    x: 317,
    y: 83,
    width: 31,
    height: 28,
    rotation: 0,
    id: 25,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration5.svg',
    x: 37,
    y: 30,
    width: 28,
    height: 28,
    rotation: 0,
    id: 26,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration8.svg',
    x: 518,
    y: 176,
    width: 49,
    height: 39,
    rotation: 0,
    id: 27,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration9.svg',
    x: 329,
    y: 324,
    width: 32,
    height: 27,
    rotation: 0,
    id: 28,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration2.svg',
    x: 147,
    y: 22,
    width: 19,
    height: 26,
    rotation: 0,
    id: 29,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration11.svg',
    x: 89,
    y: 150,
    width: 38,
    height: 35,
    rotation: 0,
    id: 30,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration6.svg',
    x: 594,
    y: 121,
    width: 34,
    height: 29,
    rotation: 0,
    id: 31,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration3.svg',
    x: 534,
    y: 32,
    width: 21,
    height: 21,
    rotation: 0,
    id: 32,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration10.svg',
    x: 137,
    y: 251,
    width: 68,
    height: 58,
    rotation: 0,
    id: 33,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration13.svg',
    x: 470,
    y: 252,
    width: 30,
    height: 55,
    rotation: 0,
    id: 34,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration12.svg',
    x: 589,
    y: 260,
    width: 26,
    height: 33,
    rotation: 0,
    id: 35,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration7.svg',
    x: 169,
    y: 112,
    width: 19,
    height: 24,
    rotation: 0,
    id: 36,
  },
  {
    contentType: 'QUESTION_HEADER',
    text: 'How did joining MCL-ACM help you?',
    x: 145,
    y: 147.5,
    rotation: 2.73,
  },
];
