export default [
  {
    contentType: 'TEXT',
    text: 'By joining MCL-ACM I got a chance to make new friends as well as develop my social and programming skills.',
    x: 175,
    y: 190,
    width: 100,
    height: 21,
    fontFamily: 'Itim',
    fontSize: 6,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'It helped me with my academics, as well as developing my programming skills',
    x: 206,
    y: 483,
    width: 85,
    height: 30,
    fontFamily: 'Caveat',
    fontSize: 8,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: 'It let me explore various paths to improve upon myself',
    x: 237,
    y: 531,
    width: 45,
    height: 24,
    fontFamily: 'Covered By Your Grace',
    fontSize: 6,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: 'I am more confident in leading, socializing, and communicating with seniors when I need help with my tasks.',
    x: 64,
    y: 73,
    width: 100,
    height: 40,
    fontFamily: 'Kalam',
    fontSize: 6,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: 'It helps me benefit my studies and make social to my org mates',
    x: 128,
    y: 574,
    width: 46,
    height: 40,
    fontFamily: 'Mali',
    fontSize: 6,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'It helped me with my studies',
    x: 134,
    y: 541,
    width: 46,
    height: 18,
    fontFamily: 'Permanent Marker',
    fontSize: 6,
    lineHeight: '1.8',
  },
  {
    contentType: 'TEXT',
    text: 'MCL-ACM helped improve my ability to communicate with other people and learning technical topics about programming by being helped by my fellow members',
    x: 209,
    y: 65,
    width: 89,
    height: 48,
    fontFamily: 'Architects Daughter',
    fontSize: 6,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'I learned to collaborate with different people and whenever you have problem on your acads-fellow acm members will try to help you.',
    x: 15,
    y: 430,
    width: 100,
    height: 28,
    fontFamily: 'Pangolin',
    fontSize: 6,
    lineHeight: '1.2',
  },
  {
    contentType: 'TEXT',
    text: "They're a big help esp. sa exam, may review sessions na ginagawa and matututo ka kahit naglu-lurk lang 😅😂",
    x: 24,
    y: 17,
    width: 85,
    height: 44,
    fontFamily: 'Sriracha',
    fontSize: 6,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: 'Joining MCL-ACM helped me connect with people more than what i currently have in my social bubble especially since we have our common interests.',
    x: 151,
    y: 398,
    width: 55,
    height: 56,
    fontFamily: 'Gochi Hand',
    fontSize: 6,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'I was able to interact with people that have the same interest as me in terms of computing and tech.',
    x: 129,
    y: 16,
    width: 107,
    height: 39,
    fontFamily: 'Shadows Into Light',
    fontSize: 8,
    lineHeight: '1.5',
  },
  {
    contentType: 'TEXT',
    text: 'It helped me become a better programmer. Being surrounded with amazing programmers, I got more motivated to be better',
    x: 138,
    y: 132,
    width: 89,
    height: 36,
    fontFamily: 'Patrick Hand',
    fontSize: 7,
    lineHeight: '1.5',
  },
  {
    contentType: 'TEXT',
    text: 'It helped me think on how to answer programming challenges more efficiently and discover more frameworks and algorithms that are used in some situations.',
    x: 28,
    y: 360,
    width: 67,
    height: 56,
    fontFamily: 'Neucha',
    fontSize: 7,
    lineHeight: '1.2',
  },
  {
    contentType: 'TEXT',
    text: 'It helps me to communicate better with others and learn new things from them',
    x: 238,
    y: 125,
    width: 100,
    height: 48,
    fontFamily: 'Merienda',
    fontSize: 8,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'It helped me connect to great people that have the same interest as me.',
    x: 227,
    y: 448,
    width: 120,
    height: 24,
    fontFamily: 'Rock Salt',
    fontSize: 5,
    lineHeight: '2.5',
  },
  {
    contentType: 'TEXT',
    text: 'It helps me improve my socializing skills and learn some programming lessons',
    x: 278,
    y: 17,
    width: 68,
    height: 36,
    fontFamily: 'Nothing You Could Do',
    fontSize: 7,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'I think that it made me aware of what my skill and abilities are capable of.',
    x: 304,
    y: 374,
    width: 36,
    height: 56,
    fontFamily: 'Comic Neue',
    fontSize: 7,
    lineHeight: '1.3',
  },
  {
    contentType: 'TEXT',
    text: 'MCL-ACM has helped me by getting to interact with like minded people that have an interest in the field of computing. Not only that, but MCL-ACM has events that piqued my interest.',
    x: 27,
    y: 184,
    width: 135,
    height: 44,
    fontFamily: 'Amatic SC',
    fontSize: 9,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'As an MITL student, joining ACM helped me connect with CCIS students that has advance knowledge in the field of computing. Collaborating and having friendships along the way heheh',
    x: 73,
    y: 466,
    width: 116,
    height: 60,
    fontFamily: 'Gloria Hallelujah',
    fontSize: 6,
    lineHeight: '2',
  },
  {
    contentType: 'TEXT',
    text: 'I made a lot of great friends and it made me confident socializing with others.',
    x: 78,
    y: 238,
    width: 88,
    height: 33,
    fontFamily: 'Handlee',
    fontSize: 8,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'It help me to grow as a person especially when I became the president.',
    x: 131,
    y: 366,
    width: 124,
    height: 18,
    fontFamily: 'Berkshire Swash',
    fontSize: 7,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'with all the seminars, peer mentoring, and my seniors willing to answer all of my questions related to coding, my coding journey was a breeze.',
    x: 254,
    y: 221,
    width: 73,
    height: 54,
    fontFamily: 'Nanum Pen Script',
    fontSize: 7,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'Joining MCL-ACM helped me meet new people, improve my skills (programming, leadership, etc.), and go out of my comfort zone',
    x: 13,
    y: 123,
    width: 69,
    height: 50,
    fontFamily: 'Amita',
    fontSize: 5,
    lineHeight: '1.8',
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration1.svg',
    x: 15,
    y: 75,
    width: 33,
    height: 35,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration4.svg',
    x: 307,
    y: 72,
    width: 31,
    height: 28,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration5.svg',
    x: 95,
    y: 139,
    width: 28,
    height: 28,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration8.svg',
    x: 187,
    y: 225,
    width: 49,
    height: 39,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration9.svg',
    x: 105,
    y: 399,
    width: 32,
    height: 27,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration2.svg',
    x: 173,
    y: 80,
    width: 19,
    height: 26,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration11.svg',
    x: 19,
    y: 478,
    width: 38,
    height: 35,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration6.svg',
    x: 301,
    y: 182,
    width: 34,
    height: 29,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration3.svg',
    x: 243,
    y: 30,
    width: 21,
    height: 21,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration10.svg',
    x: 220,
    y: 379,
    width: 68,
    height: 58,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration13.svg',
    x: 193,
    y: 557,
    width: 30,
    height: 55,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration12.svg',
    x: 303,
    y: 498,
    width: 26,
    height: 33,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/join/joiningDecoration7.svg',
    x: 32,
    y: 240,
    width: 19,
    height: 24,
    rotation: 0,
  },
];
