const content = [
  {
    contentType: 'TEXT',
    text: 'If they want to gain new learnings, improve their skills and at the same have fun with other people that shares the same interest with them. MCL-ACM can give them that.',
    x: 235,
    y: 410,
    width: 73,
    height: 64,
    fontFamily: 'Itim',
    fontSize: 7,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'Join the publication committee :D and enjoy',
    x: 253,
    y: 242,
    width: 88,
    height: 26,
    fontFamily: 'Caveat',
    fontSize: 10,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: "Make the most of the choices given to you, and don't be afraid to take the chance.",
    x: 166,
    y: 242,
    width: 72,
    height: 30,
    fontFamily: 'Amita',
    fontSize: 5,
    lineHeight: '2.3',
  },
  {
    contentType: 'TEXT',
    text: 'Make MCL-ACM your playground for making new friends, learning new things (especially about programming), and sharing to others :D',
    x: 133,
    y: 545,
    width: 83,
    height: 66,
    fontFamily: 'Kalam',
    fontSize: 7,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: 'Masaya and exciting maging MCL-ACM member. Join na kayo, hehehehehe',
    x: 243,
    y: 137,
    width: 100,
    height: 40,
    fontFamily: 'Mali',
    fontSize: 8,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'sali naa!',
    x: 45,
    y: 428,
    width: 54,
    height: 19,
    fontFamily: 'Architects Daughter',
    fontSize: 14,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'Do not be afraid to join an organization because at the end it will help you with your career.',
    x: 18,
    y: 101,
    width: 85,
    height: 40,
    fontFamily: 'Pangolin',
    fontSize: 8,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'our org is cool',
    x: 131,
    y: 26,
    width: 72,
    height: 13,
    fontFamily: 'Gochi Hand',
    fontSize: 11,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'Is to invest fully in this organization. Because it will definitely benefit you.',
    x: 62,
    y: 462,
    width: 113,
    height: 26,
    fontFamily: 'Shadows Into Light',
    fontSize: 8,
    lineHeight: '1.7',
  },
  {
    contentType: 'TEXT',
    text: "Be able to use the skills you've learned in class ,learn how to engage with diverse groups of people and you'll be able to give back to the community(Tech Events/Seminars).",
    x: 26,
    y: 502,
    width: 115,
    height: 32,
    fontFamily: 'Handlee',
    fontSize: 6,
    lineHeight: '1.8',
  },
  {
    contentType: 'TEXT',
    text: 'Have a goal in mind then achieve it with passion and good luck to all!',
    x: 70,
    y: 149,
    width: 100,
    height: 30,
    fontFamily: 'Permanent Marker',
    fontSize: 7,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: 'Always strive to be the best, failure is success in progress.',
    x: 227,
    y: 371,
    width: 111,
    height: 24,
    fontFamily: 'Patrick Hand',
    fontSize: 9,
    lineHeight: '1.8',
  },
  {
    contentType: 'TEXT',
    text: 'You can only learn to code until you type it.',
    x: 276.81,
    y: 191,
    width: 64,
    height: 30,
    fontFamily: 'Neucha',
    fontSize: 9,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'What I will say is that you will not regret joining us.',
    x: 21,
    y: 379,
    width: 100,
    height: 36,
    fontFamily: 'Merienda',
    fontSize: 8,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: "Join us, it'll be fun.",
    x: 74,
    y: 74,
    width: 85,
    height: 17,
    fontFamily: 'Rock Salt',
    fontSize: 7,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: "Work hard and don't stop learning",
    x: 21,
    y: 22,
    width: 42,
    height: 40,
    fontFamily: 'Comic Neue',
    fontSize: 9,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: "Just keep joining ACM's events, not only it is fun, there's prizes and you learn a lot of stuffs too.",
    x: 125,
    y: 104,
    width: 154,
    height: 18,
    fontFamily: 'Berkshire Swash',
    fontSize: 7,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: 'the activities are fun and not always serious, and the people are nice, so do not feel anxious about the pressure of being a member',
    x: 209,
    y: 494,
    width: 124,
    height: 33,
    fontFamily: 'Amatic SC',
    fontSize: 9,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'I recommend ACM for students who has an interest in the field of technology and to further our studies in the field of computing that are outside from our curriculum.',
    x: 225,
    y: 17,
    width: 116,
    height: 60,
    fontFamily: 'Gloria Hallelujah',
    fontSize: 6,
    lineHeight: '2',
  },
  {
    contentType: 'TEXT',
    text: "With us, we will be able to hone your programming skills and you'll be able to meet people who could be your peers throughout your stay in MCL :D",
    x: 33,
    y: 197,
    width: 94,
    height: 72,
    fontFamily: 'Indie Flower',
    fontSize: 8,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: 'MCL-ACM is the organization that will push your abilities to its peak. There are also lot of fun activities where you can learn something',
    x: 147,
    y: 364,
    width: 70,
    height: 88,
    fontFamily: 'Nanum Pen',
    fontSize: 9,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'Grab the opportunity to join an organization in college, it will be a great experience',
    x: 137,
    y: 186,
    width: 72,
    height: 44,
    fontFamily: 'Covered By Your Grace',
    fontSize: 8,
    lineHeight: '1.3',
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration2.svg',
    x: 167.9,
    y: 52.08,
    width: 36.94,
    height: 35.92,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration1.svg',
    x: 74.79,
    y: 21.07,
    width: 39.53,
    height: 37.93,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration10.svg',
    x: 197,
    y: 447,
    width: 24.15,
    height: 23.17,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration12.svg',
    x: 228.56,
    y: 541.37,
    width: 28.44,
    height: 27.66,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration7.svg',
    x: 104.29,
    y: 398.62,
    width: 31.71,
    height: 30.84,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration8.svg',
    x: 316.66,
    y: 412.82,
    width: 21.34,
    height: 20.75,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration9.svg',
    x: 21,
    y: 451,
    width: 26.66,
    height: 25.92,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration11.svg',
    x: 158.55,
    y: 500.64,
    width: 32.25,
    height: 31.36,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration3.svg',
    x: 288,
    y: 84,
    width: 46.89,
    height: 45.6,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration5.svg',
    x: 187,
    y: 136,
    width: 39.2,
    height: 38.12,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration4.svg',
    x: 23.56,
    y: 157.37,
    width: 28.44,
    height: 27.66,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/aspiring/aspiringDecoration6.svg',
    x: 233,
    y: 198,
    width: 31.26,
    height: 30.4,
    rotation: 0,
  },
  {
    contentType: 'QUESTION_HEADER',
    text: 'Do you have a message for aspiring members of MCL-ACM?',
    x: 15,
    y: 291.43,
    rotation: -1.39,
  },
];

const indexedContent = content.map((e, index) => ({
  ...e,
  id: index + 1,
}));

export default indexedContent;
