export default [
  {
    contentType: 'TEXT',
    text: 'Most memorable moment is the Minecraft event of ACM during the anniversary month.',
    x: 246,
    y: 15,
    width: 100,
    height: 33,
    fontFamily: 'Kalam',
    fontSize: 7,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'My first meeting with the MCL ACM member and sir Ian',
    x: 16,
    y: 511,
    width: 93,
    height: 30,
    fontFamily: 'Mali',
    fontSize: 8,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'My most memorable moment in MCL-ACM was when I was preparing the publication materials for the anniversary month events.',
    x: 28,
    y: 64,
    width: '115',
    height: 40,
    fontFamily: 'Architects Daughter',
    fontSize: 7,
    lineHeight: '1.5',
  },
  {
    contentType: 'TEXT',
    text: 'Pretty much every hangout/playing event where I get to hangout and talk with other members of the org.',
    x: 22,
    y: 456,
    width: 107,
    height: 27,
    fontFamily: 'Pangolin',
    fontSize: 7,
    lineHeight: '1.3',
  },
  {
    contentType: 'TEXT',
    text: 'Fun activities such as games and hangouts.',
    x: 245,
    y: 144,
    width: 99,
    height: 24,
    fontFamily: 'Sriracha',
    fontSize: 7,
    lineHeight: '1.5',
  },
  {
    contentType: 'TEXT',
    text: 'Planning the Craftivities and joining the event',
    x: 307.05,
    y: 430,
    width: 40,
    height: 45,
    fontFamily: 'Gochi Hand',
    fontSize: 8,
    lineHeight: '1.2',
  },
  {
    contentType: 'TEXT',
    text: 'Being able to hang out with other members to create memories in an online setting.',
    x: 33,
    y: 364,
    width: 90,
    height: 27,
    fontFamily: 'Permanent Marker',
    fontSize: 6,
    lineHeight: '1.5',
  },
  {
    contentType: 'TEXT',
    text: 'For me General Assembly that happens every month- because all ACM members gathers together and also we discuss here exciting events that will be performed in the future.',
    x: 223,
    y: 234,
    width: 123,
    height: '50',
    fontFamily: 'Patrick Hand',
    fontSize: 7,
    lineHeight: '1.6',
  },
  {
    contentType: 'TEXT',
    text: 'i guess me passing the coding challenge.',
    x: 141,
    y: 470,
    width: '65',
    height: 18,
    fontFamily: 'Neucha',
    fontSize: 8,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'the recent swimming party',
    x: 188,
    y: 125,
    width: 52,
    height: 18,
    fontFamily: 'Merienda',
    fontSize: 6,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'Study Groups',
    x: 177,
    y: 165,
    width: 52,
    height: 10,
    fontFamily: 'Comic Neue',
    fontSize: 9,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'My most memorable moment is when we get together and enjoy activities.',
    x: 27,
    y: 127,
    width: 40,
    height: 63,
    fontFamily: 'Nothing You Could Do',
    fontSize: 7,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'Hour of Code 2019 at pizza party nung face-to-face pa :)',
    x: 216,
    y: 500,
    width: 65,
    height: 30,
    fontFamily: 'Indie Flower',
    fontSize: 7,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'Taking that entrance Member test without a partner ðŸ˜‚',
    x: 230,
    y: 542,
    width: '75',
    height: 20,
    fontFamily: 'Rock Salt',
    fontSize: 4,
    lineHeight: '2',
  },
  {
    contentType: 'TEXT',
    text: 'The Year-end party was pretty great, I was able to personally meet other members, really pog event.',
    x: 18,
    y: 14,
    width: '110',
    height: 39,
    fontFamily: 'Amatic SC',
    fontSize: 10,
    lineHeight: '1.2',
  },
  {
    contentType: 'TEXT',
    text: 'Not exactly a specific moment but our activities and events are very memorable as most of us, or all of us in that matter contributed on the planning and preparation of those.',
    x: 117,
    y: 575,
    width: 129,
    height: 40,
    fontFamily: 'Gloria Hallelujah',
    fontSize: 5,
    lineHeight: '1.7',
  },
  {
    contentType: 'TEXT',
    text: 'Hour of Code',
    x: 133,
    y: 260,
    width: 88,
    height: 13,
    fontFamily: 'Handlee',
    fontSize: 10,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'Getting to develop a website with the RnD committee',
    x: 25,
    y: 236,
    width: 110,
    height: 42,
    fontFamily: 'Nanum Pen Script',
    fontSize: 11,
    lineHeight: 1,
  },
  {
    contentType: 'TEXT',
    text: 'I enjoyed all the Craftivities :D (Special mention to Hour of Code 2019)',
    x: 138,
    y: 386,
    width: 57,
    height: 60,
    fontFamily: 'Covered By Your Grace',
    fontSize: 9,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'When I was a President, I always remember initiate a meeting. And it was fun organizing events for our members, the MCL community, and computing-interested community.',
    x: '156',
    y: 16,
    width: '68',
    height: 96,
    fontFamily: 'Amita',
    fontSize: 6,
    lineHeight: '2',
  },
  {
    contentType: 'TEXT',
    text: 'The year end party of 2022 is my most memorable moment in the MCL-ACM because I was able to meet my orgmates and adviser for the first time.',
    x: 217,
    y: 362,
    width: 115,
    height: 65,
    fontFamily: 'Caveat',
    fontSize: 10,
    lineHeight: '1.4',
  },
  {
    contentType: 'TEXT',
    text: 'Overall my most memorable moment in MCL-ACM is the process of preparing and executing events with the other members for others to benefit and enjoy.',
    x: 97,
    y: 190,
    width: 124,
    height: 32,
    fontFamily: 'Itim',
    fontSize: 7,
    lineHeight: '1.3',
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorablePhoto1.png',
    x: 77.16,
    y: 110.58,
    width: 80.21,
    height: 60.22,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorablePhoto6.png',
    x: 123,
    y: 500,
    width: 78.86,
    height: 48.74,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorablePhoto5.png',
    x: 214,
    y: 436.73,
    width: 89.11,
    height: 62.13,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorablePhoto2.png',
    x: 249,
    y: 73,
    width: 100.77,
    height: 62.84,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorablePhoto3.png',
    x: 267.77,
    y: 174.66,
    width: 73.45,
    height: 54.58,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorablePhoto4.png',
    x: 35,
    y: 400.21,
    width: 88.1,
    height: 49.23,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration1.svg',
    x: 125,
    y: 35,
    width: 16.39,
    height: 21.75,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration2.svg',
    x: 224.65,
    y: 55.34,
    width: 44.4,
    height: 50.2,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration3.svg',
    x: 286,
    y: 55,
    width: 29,
    height: 16,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration4.svg',
    x: 17,
    y: 115,
    width: 54.55,
    height: 82.67,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration5.svg',
    x: 153.79,
    y: 138.02,
    width: 34.05,
    height: 29.34,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration6.svg',
    x: 18,
    y: 205,
    width: 26.12,
    height: 28.45,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration7.svg',
    x: 121,
    y: 229,
    width: 82,
    height: 12.19,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration8.svg',
    x: 238,
    y: 204,
    width: 28.45,
    height: 22.35,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration9.svg',
    x: 4.5,
    y: 375.49,
    width: 41.66,
    height: 41.49,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration10.svg',
    x: 196,
    y: 427,
    width: 24.62,
    height: 33.36,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration11.svg',
    x: 106.51,
    y: 485.95,
    width: 13.89,
    height: 22.06,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration12.svg',
    x: 298,
    y: 501,
    width: 26.24,
    height: 28.14,
    rotation: 0,
  },
  {
    contentType: 'IMAGE',
    image: '/anniversary/2022/moments/memorableDecoration13.svg',
    x: 159,
    y: 561,
    width: 42,
    height: 9,
    rotation: 0,
  },
];
