# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # https://github.com/actions/setup-node#usage
    - uses: actions/setup-node@v3.0.0
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build
    # Deploy the gatsby build to Netlify
    - uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --dir=public --prodIfUnlocked
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
